---
title: "Lab 00 - Hello Class!"
date: " `r Sys.Date()`"
author: "Tanzy Love"

output: md_document
---


# Introduction

This is a demonstration file to go in lecture 01. 
This is your short verison to work on.

# Data

Now, for the statistics!!!!!!

Read in some data?

```{r hotdogs}
hotdogs=read.table("Hdcalsod.TXT", header=T)

colnames(hotdogs)
hotdogs$Calories

attach(hotdogs)

plot(Calories, Sodium, xlab="Calories", ylab="Sodium", pch=16)
cor(Calories, Sodium)

plot(Calories, Sodium, xlab="Calories", ylab="Sodium", 
	col=factor(Type), pch=16)
legend("bottomright", levels(factor(Type)), col=1:3, pch=1)
```

Let's try a different data set. This one about 50 states.

```{r raingrad}
hsgrads=read.table("raingrad.TXT", header=T, sep="\t")
attach(hsgrads)

plot(Rain, Education, 
      xlab="Rainfall", ylab="Average Grade Level", pch=16)
cor(Rain, Education)

args(cor)
```

And one final set of flying times.

```{r delta}
delta=read.table("Deltafly.TXT", header=T)
attach(delta)

hist(Miles, xlab="Distance (Miles)")
hist(DepHr, main=NULL, xlab="Departure Hour (24hour)", xlim=c(0,24))
hist(TravTime, main=NULL, xlab="Travel Time (Hours)")

plot(Miles, TravTime, xlab="Distance (Miles)", ylab="Travel Time (Hours)")
cor(Miles, TravTime)

reg.line=lm(TravTime~Miles) #calcuate the regression line for the Delta data
summary(reg.line)
abline(reg.line, col=2, lwd=2)

par(mfrow=c(1,2)) #make both plots appear together
plot(reg.line, which=1:2)  # plot residual assumption plots
par(mfrow=c(1,1)) #make only one plot appear at a time
```

You may not be able to do this on your own after lecture 1, so don't worry about it!!
